[
  {
    "caliber_mm": 4.6,
    "name": "4.6×30mm HK",
    "type": "AP",
    "mass_kg": 0.002,
    "energy_j": 520,
    "speed_m_s": 720,
    "penetration_mm": {"100m": 2, "200m": 1.5},
    "lethal_armor_mm": 2,
    "notes": "Heckler & Koch PDW round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 6.8,
    "name": "6.8 SPC",
    "type": "AP",
    "mass_kg": 0.0085,
    "energy_j": 2500,
    "speed_m_s": 800,
    "penetration_mm": {"100m": 5, "500m": 4},
    "lethal_armor_mm": 5,
    "notes": "US modern short-range rifle round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 7.62,
    "name": "7.62×54mmR",
    "type": "AP",
    "mass_kg": 0.0096,
    "energy_j": 3600,
    "speed_m_s": 830,
    "penetration_mm": {"100m": 7, "500m": 6},
    "lethal_armor_mm": 7,
    "notes": "Russian sniper & MG round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 8,
    "name": "8×57mm IS",
    "type": "AP",
    "mass_kg": 0.012,
    "energy_j": 4000,
    "speed_m_s": 760,
    "penetration_mm": {"100m": 8, "500m": 6},
    "lethal_armor_mm": 8,
    "notes": "German WW1 & WW2 rifles",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 12.7,
    "name": ".50 BMG M33",
    "type": "Ball",
    "mass_kg": 0.046,
    "energy_j": 15000,
    "speed_m_s": 890,
    "penetration_mm": {"100m": 19, "500m": 17},
    "lethal_armor_mm": 19,
    "notes": "US heavy MG standard ball round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 14.5,
    "name": "14.5×114mm API B32",
    "type": "API",
    "mass_kg": 0.064,
    "energy_j": 22000,
    "speed_m_s": 1000,
    "penetration_mm": {"100m": 32, "500m": 28},
    "lethal_armor_mm": 32,
    "notes": "Soviet heavy MG anti-armor",
    "source": "BBTI"
  },
  {
    "caliber_mm": 20,
    "name": "20×139mm Oerlikon",
    "type": "APDS",
    "mass_kg": 0.150,
    "energy_j": 50000,
    "speed_m_s": 900,
    "penetration_mm": {"100m": 60, "500m": 50},
    "lethal_armor_mm": 60,
    "notes": "Aircraft cannon round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 23,
    "name": "23×115mm",
    "type": "API",
    "mass_kg": 0.190,
    "energy_j": 80000,
    "speed_m_s": 720,
    "penetration_mm": {"100m": 80, "500m": 70},
    "lethal_armor_mm": 80,
    "notes": "Soviet aircraft cannon AP round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 25,
    "name": "25×137mm M792",
    "type": "HEI",
    "mass_kg": 0.250,
    "energy_j": 100000,
    "speed_m_s": 1100,
    "penetration_mm": {"100m": 85, "500m": 80},
    "lethal_armor_mm": 85,
    "notes": "US autocannon HEI round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 30,
    "name": "30×173mm PGU-13/B",
    "type": "HEI",
    "mass_kg": 0.750,
    "energy_j": 200000,
    "speed_m_s": 1050,
    "penetration_mm": {"100m": 100, "500m": 90},
    "lethal_armor_mm": 100,
    "notes": "US aircraft HEI round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 37,
    "name": "37×258mm Bofors",
    "type": "AP",
    "mass_kg": 0.950,
    "energy_j": 320000,
    "speed_m_s": 800,
    "penetration_mm": {"100m": 150, "500m": 130},
    "lethal_armor_mm": 150,
    "notes": "Swedish naval/AA round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 40,
    "name": "40×365mm R Bofors",
    "type": "HE",
    "mass_kg": 0.900,
    "energy_j": 300000,
    "speed_m_s": 780,
    "penetration_mm": {"100m": 140, "500m": 120},
    "lethal_armor_mm": 140,
    "notes": "Naval AA round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 50,
    "name": "50×420mm",
    "type": "AP",
    "mass_kg": 1.80,
    "energy_j": 800000,
    "speed_m_s": 850,
    "penetration_mm": {"100m": 200, "500m": 180},
    "lethal_armor_mm": 200,
    "notes": "WW2 anti-tank gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 57,
    "name": "57×348mm APDS",
    "type": "APDS",
    "mass_kg": 2.30,
    "energy_j": 1.2e6,
    "speed_m_s": 1050,
    "penetration_mm": {"100m": 200, "500m": 180},
    "lethal_armor_mm": 200,
    "notes": "British AT gun round",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 75,
    "name": "75×350mm R KwK 42",
    "type": "APCR",
    "mass_kg": 6.80,
    "energy_j": 3.0e6,
    "speed_m_s": 900,
    "penetration_mm": {"100m": 250, "500m": 220},
    "lethal_armor_mm": 250,
    "notes": "WW2 German tank gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 88,
    "name": "88×571mm KwK 36",
    "type": "APC",
    "mass_kg": 10.0,
    "energy_j": 5.0e6,
    "speed_m_s": 820,
    "penetration_mm": {"100m": 300, "500m": 270},
    "lethal_armor_mm": 300,
    "notes": "WW2 German Tiger I main gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 90,
    "name": "90mm T15",
    "type": "AP",
    "mass_kg": 10.5,
    "energy_j": 4.8e6,
    "speed_m_s": 810,
    "penetration_mm": {"100m": 320, "500m": 290},
    "lethal_armor_mm": 320,
    "notes": "WW2 US tank gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 105,
    "name": "105mm M68",
    "type": "APFSDS",
    "mass_kg": 15.0,
    "energy_j": 1.2e7,
    "speed_m_s": 900,
    "penetration_mm": {"100m": 400, "500m": 350},
    "lethal_armor_mm": 400,
    "notes": "NATO MBT gun",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 120,
    "name": "120mm M829A3",
    "type": "APFSDS",
    "mass_kg": 10.5,
    "energy_j": 1.5e7,
    "speed_m_s": 1700,
    "penetration_mm": {"100m": 550, "500m": 500},
    "lethal_armor_mm": 550,
    "notes": "Modern US MBT penetrator",
    "source": ""
  },
    {
    "caliber_mm": 125,
    "name": "125mm 3BM42",
    "type": "APFSDS",
    "mass_kg": 8.5,
    "energy_j": 1.3e7,
    "speed_m_s": 1700,
    "penetration_mm": {"100m": 500, "500m": 450},
    "lethal_armor_mm": 500,
    "notes": "Modern Russian MBT penetrator",
    "source": "BBTI"
  }
]

[
  {
    "vehicle_name": "M1A2 Abrams",
    "type": "Main Battle Tank",
    "armor_mm": 600,
    "weight_tons": 62,
    "max_speed_kph": 67,
    "engine_power_hp": 1500,
    "crew": 4,
    "armor_material": "Composite + Chobham",
    "notes": "Modern US MBT",
    "source": "AFV Database"
  },
  {
    "vehicle_name": "Merkava Mk4",
    "type": "Main Battle Tank",
    "armor_mm": 650,
    "weight_tons": 65,
    "max_speed_kph": 64,
    "engine_power_hp": 1500,
    "crew": 4,
    "armor_material": "Composite + ERA",
    "notes": "Israeli MBT",
    "source": "AFV Database"
  },
  {
    "vehicle_name": "Leclerc",
    "type": "Main Battle Tank",
    "armor_mm": 650,
    "weight_tons": 57,
    "max_speed_kph": 72,
    "engine_power_hp": 1500,
    "crew": 3,
    "armor_material": "Composite",
    "notes": "French MBT",
    "source": "AFV Database"
  },
  {
    "vehicle_name": "CV90 MkIV",
    "type": "Infantry Fighting Vehicle",
    "armor_mm": 50,
    "weight_tons": 35,
    "max_speed_kph": 70,
    "engine_power_hp": 900,
    "crew": 3,
    "armor_material": "Composite + ERA",
    "notes": "Swedish IFV",
    "source": "AFV Database"
  },
  {
    "vehicle_name": "Stryker ICV",
    "type": "Armored Personnel Carrier",
    "armor_mm": 30,
    "weight_tons": 16,
    "max_speed_kph": 97,
    "engine_power_hp": 350,
    "crew": 3,
    "armor_material": "Steel + optional ERA",
    "notes": "US wheeled APC",
    "source": "AFV Database"
  }
][
  {
    "caliber_mm": 5.56,
    "name": "5.56×45mm NATO M855",
    "type": "Ball",
    "mass_kg": 0.004,
    "energy_j": 1800,
    "speed_m_s": 940,
    "penetration_mm": {"100m": 3, "500m": 2},
    "lethal_armor_mm": 3,
    "notes": "Standard NATO rifle round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 5.45,
    "name": "5.45×39mm 7N6",
    "type": "AP",
    "mass_kg": 0.0034,
    "energy_j": 1600,
    "speed_m_s": 900,
    "penetration_mm": {"100m": 3, "500m": 2},
    "lethal_armor_mm": 3,
    "notes": "Soviet/Russian rifle round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 7.62,
    "name": "7.62×39mm M43",
    "type": "Ball",
    "mass_kg": 0.008,
    "energy_j": 1800,
    "speed_m_s": 720,
    "penetration_mm": {"100m": 4, "500m": 3},
    "lethal_armor_mm": 4,
    "notes": "AK-47 standard round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 7.62,
    "name": "7.62×51mm NATO M80",
    "type": "Ball",
    "mass_kg": 0.0095,
    "energy_j": 3600,
    "speed_m_s": 840,
    "penetration_mm": {"100m": 6, "500m": 5},
    "lethal_armor_mm": 6,
    "notes": "Standard NATO rifle/machine gun round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 7.62,
    "name": "7.62×51mm M61",
    "type": "AP",
    "mass_kg": 0.010,
    "energy_j": 3800,
    "speed_m_s": 850,
    "penetration_mm": {"100m": 7, "500m": 6},
    "lethal_armor_mm": 7,
    "notes": "NATO AP round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 8.8,
    "name": "8.8×56mm R PzGr",
    "type": "APCR",
    "mass_kg": 0.015,
    "energy_j": 5000,
    "speed_m_s": 800,
    "penetration_mm": {"100m": 10, "500m": 8},
    "lethal_armor_mm": 10,
    "notes": "WW2 German tank round",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 12.7,
    "name": ".50 BMG API M2",
    "type": "AP",
    "mass_kg": 0.046,
    "energy_j": 16000,
    "speed_m_s": 890,
    "penetration_mm": {"100m": 20, "500m": 18},
    "lethal_armor_mm": 20,
    "notes": "Heavy MG AP round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 14.5,
    "name": "14.5×114mm API M91",
    "type": "API",
    "mass_kg": 0.064,
    "energy_j": 22000,
    "speed_m_s": 1000,
    "penetration_mm": {"100m": 32, "500m": 28},
    "lethal_armor_mm": 32,
    "notes": "Heavy anti-armor round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 20,
    "name": "20×110mm Hispano AP",
    "type": "AP",
    "mass_kg": 0.130,
    "energy_j": 45000,
    "speed_m_s": 850,
    "penetration_mm": {"100m": 55, "500m": 50},
    "lethal_armor_mm": 55,
    "notes": "Aircraft cannon AP round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 20,
    "name": "20×139mm Oerlikon AP",
    "type": "AP",
    "mass_kg": 0.150,
    "energy_j": 50000,
    "speed_m_s": 900,
    "penetration_mm": {"100m": 60, "500m": 55},
    "lethal_armor_mm": 60,
    "notes": "Aircraft cannon AP round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 25,
    "name": "25×137mm APDS",
    "type": "APDS-T",
    "mass_kg": 0.250,
    "energy_j": 100000,
    "speed_m_s": 1100,
    "penetration_mm": {"100m": 90, "500m": 85},
    "lethal_armor_mm": 90,
    "notes": "US autocannon APDS-T",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 30,
    "name": "30×173mm APDS",
    "type": "APDS",
    "mass_kg": 0.720,
    "energy_j": 200000,
    "speed_m_s": 1050,
    "penetration_mm": {"100m": 120, "500m": 110},
    "lethal_armor_mm": 120,
    "notes": "US aircraft cannon AP round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 37,
    "name": "37×258mm Bofors AP",
    "type": "AP",
    "mass_kg": 0.900,
    "energy_j": 300000,
    "speed_m_s": 800,
    "penetration_mm": {"100m": 150, "500m": 130},
    "lethal_armor_mm": 150,
    "notes": "Naval/AA AP round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 40,
    "name": "40×311mm Bofors AP",
    "type": "AP",
    "mass_kg": 0.850,
    "energy_j": 290000,
    "speed_m_s": 780,
    "penetration_mm": {"100m": 140, "500m": 120},
    "lethal_armor_mm": 140,
    "notes": "Naval/AA round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 50,
    "name": "50×420mm AP",
    "type": "AP",
    "mass_kg": 1.800,
    "energy_j": 800000,
    "speed_m_s": 850,
    "penetration_mm": {"100m": 200, "500m": 180},
    "lethal_armor_mm": 200,
    "notes": "WW2 AT gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 57,
    "name": "57×348mm APDS",
    "type": "APDS",
    "mass_kg": 2.300,
    "energy_j": 1.2e6,
    "speed_m_s": 1050,
    "penetration_mm": {"100m": 200, "500m": 180},
    "lethal_armor_mm": 200,
    "notes": "British AT gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 75,
    "name": "75×350mm R APCR",
    "type": "APCR",
    "mass_kg": 6.800,
    "energy_j": 3.0e6,
    "speed_m_s": 900,
    "penetration_mm": {"100m": 250, "500m": 220},
    "lethal_armor_mm": 250,
    "notes": "WW2 German tank gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 88,
    "name": "88×571mm KwK 36 AP",
    "type": "APC",
    "mass_kg": 10.000,
    "energy_j": 5.0e6,
    "speed_m_s": 820,
    "penetration_mm": {"100m": 300, "500m": 270},
    "lethal_armor_mm": 300,
    "notes": "Tiger I main gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 90,
    "name": "90mm T15 AP",
    "type": "AP",
    "mass_kg": 10.500,
    "energy_j": 4.8e6,
    "speed_m_s": 810,
    "penetration_mm": {"100m": 320, "500m": 290},
    "lethal_armor_mm": 320,
    "notes": "WW2 US tank gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 105,
    "name": "105mm M68 APFSDS",
    "type": "APFSDS",
    "mass_kg": 15.000,
    "energy_j": 1.2e7,
    "speed_m_s": 900,
    "penetration_mm": {"100m": 400, "500m": 350},
    "lethal_armor_mm": 400,
    "notes": "NATO MBT gun",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 120,
    "name": "120mm M829A3",
    "type": "APFSDS",
    "mass_kg": 10.500,
    "energy_j": 1.5e7,
    "speed_m_s": 1700,
    "penetration_mm": {"100m": 550, "500m": 500},
    "lethal_armor_mm": 550,
    "notes": "Modern US MBT penetrator",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 125,
    "name": "125mm 3BM42 APFSDS",
    "type": "APFSDS",
    "mass_kg": 8.500,
    "energy_j": 1.3e7,
    "speed_m_s": 1700,
    "penetration_mm": {"100m": 500, "500m": 450},
    "lethal_armor_mm": 500,
    "notes": "Modern Russian MBT penetrator",
    "source": "BBTI"
  },
  {
    "caliber_mm": 140,
    "name": "140mm Rheinmetall APFSDS",
    "type": "APFSDS",
    "mass_kg": 10.000,
    "energy_j": 2.0e7,
    "speed_m_s": 1700,
    "penetration_mm": {"100m": 600, "500m": 550},
    "lethal_armor_mm": 600,
    "notes": "Experimental German MBT round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 155,
    "name": "155mm M107 HE",
    "type": "HE",
    "mass_kg": 43.000,
    "energy_j": 5.0e6,
    "speed_m_s": 800,
    "penetration_mm": {"100m": 100, "500m": 80},
    "lethal_armor_mm": 100,
    "notes": "US standard artillery shell",
    "source": "BBTI"
  },
  {
    "caliber_mm": 155,
    "name": "155mm M829A1 HEAT",
    "type": "HEAT",
    "mass_kg": 43.000,
    "energy_j": 4.5e6,
    "speed_m_s": 800,
    "penetration_mm": {"100m": 500, "500m": 450},
    "lethal_armor_mm": 500,
    "notes": "US modern MBT HEAT shell",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 203,
    "name": "203mm M115 HE",
    "type": "HE",
    "mass_kg": 91.000,
    "energy_j": 1.0e7,
    "speed_m_s": 700,
    "penetration_mm": {"100m": 150, "500m": 120},
    "lethal_armor_mm": 150,
    "notes": "US heavy artillery",
    "source": "BBTI"
  },
  {
    "caliber_mm": 240,
    "name": "240mm M240 HE",
    "type": "HE",
    "mass_kg": 150.000,
    "energy_j": 1.5e7,
    "speed_m_s": 650,
    "penetration_mm": {"100m": 200, "500m": 150},
    "lethal_armor_mm": 200,
    "notes": "Heavy siege artillery",
    "source": "BBTI"
  },
  {
    "caliber_mm": 305,
    "name": "305mm Schneider AP",
    "type": "AP",
    "mass_kg": 400.000,
    "energy_j": 4.0e7,
    "speed_m_s": 600,
    "penetration_mm": {"100m": 500, "500m": 450},
    "lethal_armor_mm": 500,
    "notes": "WW1 heavy siege gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 406,
    "name": "406mm Mark 5 AP",
    "type": "AP",
    "mass_kg": 900.000,
    "energy_j": 1.0e8,
    "speed_m_s": 700,
    "penetration_mm": {"100m": 700, "500m": 650},
    "lethal_armor_mm": 700,
    "notes": "WW2 battleship gun",
    "source": "Panzerworld"
  }
]
[
  {
    "vehicle_name": "T-14 Armata",
    "type": "Main Battle Tank",
    "armor_mm": 800,
    "weight_tons": 55,
    "max_speed_kph": 80,
    "engine_power_hp": 1500,
    "crew": 3,
    "armor_material": "Composite + ERA",
    "notes": "Modern Russian MBT",
    "source": "BBTI"
  },
  {
    "vehicle_name": "T-90M",
    "type": "Main Battle Tank",
    "armor_mm": 600,
    "weight_tons": 46,
    "max_speed_kph": 60,
    "engine_power_hp": 1130,
    "crew": 3,
    "armor_material": "Composite + ERA",
    "notes": "Modernized Russian MBT",
    "source": "BBTI"
  },
  {
    "vehicle_name": "Leopard 2A7",
    "type": "Main Battle Tank",
    "armor_mm": 700,
    "weight_tons": 62,
    "max_speed_kph": 70,
    "engine_power_hp": 1500,
    "crew": 4,
    "armor_material": "Composite + ERA",
    "notes": "Modern German MBT",
    "source": "BBTI"
  },
  {
    "vehicle_name": "Challenger 2",
    "type": "Main Battle Tank",
    "armor_mm": 650,
    "weight_tons": 62.5,
    "max_speed_kph": 59,
    "engine_power_hp": 1200,
    "crew": 4,
    "armor_material": "Composite + Chobham",
    "notes": "UK MBT",
    "source": "BBTI"
  },
  {
    "vehicle_name": "K2 Black Panther",
    "type": "Main Battle Tank",
    "armor_mm": 700,
    "weight_tons": 55,
    "max_speed_kph": 70,
    "engine_power_hp": 1500,
    "crew": 3,
    "armor_material": "Composite + ERA",
    "notes": "South Korean MBT",
    "source": "BBTI"
  },
  {
    "vehicle_name": "BMP-3",
    "type": "Infantry Fighting Vehicle",
    "armor_mm": 30,
    "weight_tons": 18.7,
    "max_speed_kph": 70,
    "engine_power_hp": 500,
    "crew": 3,
    "armor_material": "Steel + ERA",
    "notes": "Russian IFV",
    "source": "BBTI"
  },
  {
    "vehicle_name": "M2 Bradley",
    "type": "Infantry Fighting Vehicle",
    "armor_mm": 50,
    "weight_tons": 27,
    "max_speed_kph": 66,
    "engine_power_hp": 600,
    "crew": 3,
    "armor_material": "Aluminum + ERA",
    "notes": "US IFV",
    "source": "BBTI"
  },
  {
    "vehicle_name": "Puma",
    "type": "Infantry Fighting Vehicle",
    "armor_mm": 50,
    "weight_tons": 31,
    "max_speed_kph": 70,
    "engine_power_hp": 820,
    "crew": 3,
    "armor_material": "Composite + ERA",
    "notes": "German IFV",
    "source": "BBTI"
  },
  {
    "vehicle_name": "Stryker",
    "type": "Armored Personnel Carrier",
    "armor_mm": 30,
    "weight_tons": 16,
    "max_speed_kph": 97,
    "engine_power_hp": 350,
    "crew": 3,
    "armor_material": "Steel + optional ERA",
    "notes": "US wheeled APC",
    "source": "BBTI"
  },
  {
    "vehicle_name": "Boxer",
    "type": "Armored Personnel Carrier",
    "armor_mm": 35,
    "weight_tons": 33,
    "max_speed_kph": 103,
    "engine_power_hp": 530,
    "crew": 3,
    "armor_material": "Steel + Composite",
    "notes": "German/Dutch APC",
    "source": "BBTI"
  }
]
[
  {
    "caliber_mm": 7.62,
    "name": "7.62×54mmR LPS",
    "type": "AP",
    "mass_kg": 0.0096,
    "energy_j": 3500,
    "speed_m_s": 830,
    "penetration_mm": {"100m": 6, "500m": 5},
    "lethal_armor_mm": 6,
    "notes": "Russian sniper/AP round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 7.92,
    "name": "7.92×57mm Mauser S",
    "type": "AP",
    "mass_kg": 0.011,
    "energy_j": 4000,
    "speed_m_s": 760,
    "penetration_mm": {"100m": 7, "500m": 6},
    "lethal_armor_mm": 7,
    "notes": "WW2 German rifle/AP round",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 9.3,
    "name": "9.3×62mm KJG",
    "type": "AP",
    "mass_kg": 0.015,
    "energy_j": 4500,
    "speed_m_s": 720,
    "penetration_mm": {"100m": 8, "500m": 6},
    "lethal_armor_mm": 8,
    "notes": "Hunting/AP penetration round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 14.5,
    "name": "14.5×114mm BS",
    "type": "AP",
    "mass_kg": 0.064,
    "energy_j": 22000,
    "speed_m_s": 1000,
    "penetration_mm": {"100m": 32, "500m": 28},
    "lethal_armor_mm": 32,
    "notes": "Soviet heavy machine gun AP",
    "source": "BBTI"
  },
  {
    "caliber_mm": 20,
    "name": "20×102mm Vulcan AP",
    "type": "AP",
    "mass_kg": 0.099,
    "energy_j": 45000,
    "speed_m_s": 1050,
    "penetration_mm": {"100m": 55, "500m": 50},
    "lethal_armor_mm": 55,
    "notes": "US aircraft cannon",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 25,
    "name": "25×137mm M791 APDS-T",
    "type": "APDS-T",
    "mass_kg": 0.265,
    "energy_j": 1.1e5,
    "speed_m_s": 1080,
    "penetration_mm": {"100m": 95, "500m": 90},
    "lethal_armor_mm": 95,
    "notes": "US autocannon",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 30,
    "name": "30×173mm GAU-8 AP",
    "type": "AP",
    "mass_kg": 0.720,
    "energy_j": 2e5,
    "speed_m_s": 1050,
    "penetration_mm": {"100m": 120, "500m": 110},
    "lethal_armor_mm": 120,
    "notes": "A-10 aircraft cannon",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 40,
    "name": "40×311mm Bofors AP",
    "type": "AP",
    "mass_kg": 0.850,
    "energy_j": 290000,
    "speed_m_s": 780,
    "penetration_mm": {"100m": 140, "500m": 120},
    "lethal_armor_mm": 140,
    "notes": "Naval AA",
    "source": "BBTI"
  },
  {
    "caliber_mm": 50,
    "name": "50×420mm AP",
    "type": "AP",
    "mass_kg": 1.800,
    "energy_j": 800000,
    "speed_m_s": 850,
    "penetration_mm": {"100m": 200, "500m": 180},
    "lethal_armor_mm": 200,
    "notes": "WW2 AT gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 57,
    "name": "57×348mm APDS",
    "type": "APDS",
    "mass_kg": 2.300,
    "energy_j": 1.2e6,
    "speed_m_s": 1050,
    "penetration_mm": {"100m": 200, "500m": 180},
    "lethal_armor_mm": 200,
    "notes": "British AT gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 75,
    "name": "75×350mm R APCR",
    "type": "APCR",
    "mass_kg": 6.800,
    "energy_j": 3.0e6,
    "speed_m_s": 900,
    "penetration_mm": {"100m": 250, "500m": 220},
    "lethal_armor_mm": 250,
    "notes": "WW2 German tank",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 76.2,
    "name": "76.2×385mm R AP",
    "type": "AP",
    "mass_kg": 7.500,
    "energy_j": 3.2e6,
    "speed_m_s": 810,
    "penetration_mm": {"100m": 260, "500m": 230},
    "lethal_armor_mm": 260,
    "notes": "US WW2 Sherman AP",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 88,
    "name": "88×571mm KwK36 AP",
    "type": "APC",
    "mass_kg": 10.000,
    "energy_j": 5.0e6,
    "speed_m_s": 820,
    "penetration_mm": {"100m": 300, "500m": 270},
    "lethal_armor_mm": 300,
    "notes": "Tiger I gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 90,
    "name": "90mm M3 AP",
    "type": "AP",
    "mass_kg": 10.500,
    "energy_j": 4.8e6,
    "speed_m_s": 810,
    "penetration_mm": {"100m": 320, "500m": 290},
    "lethal_armor_mm": 320,
    "notes": "US WW2 Sherman gun",
    "source": "Panzerworld"
  }
]
[
  {
    "caliber_mm": 100,
    "name": "100mm D-10T AP",
    "type": "AP",
    "mass_kg": 15.600,
    "energy_j": 6.0e6,
    "speed_m_s": 900,
    "penetration_mm": {"100m": 400, "500m": 350},
    "lethal_armor_mm": 400,
    "notes": "T-54/T-55 tank gun",
    "source": "BBTI"
  },
  {
    "caliber_mm": 105,
    "name": "105mm L7 APDS",
    "type": "APDS",
    "mass_kg": 12.000,
    "energy_j": 7.0e6,
    "speed_m_s": 1_450,
    "penetration_mm": {"100m": 450, "500m": 400},
    "lethal_armor_mm": 450,
    "notes": "British/German NATO tank gun",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 105,
    "name": "105mm M456 HEAT",
    "type": "HEAT",
    "mass_kg": 12.500,
    "energy_j": 6.5e6,
    "speed_m_s": 900,
    "penetration_mm": {"100m": 500, "500m": 450},
    "lethal_armor_mm": 500,
    "notes": "US M60 tank",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 110,
    "name": "110mm APFSDS",
    "type": "APFSDS",
    "mass_kg": 14.000,
    "energy_j": 8.0e6,
    "speed_m_s": 1_600,
    "penetration_mm": {"100m": 550, "500m": 500},
    "lethal_armor_mm": 550,
    "notes": "Experimental US round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 120,
    "name": "120mm Rheinmetall L/55 APFSDS",
    "type": "APFSDS",
    "mass_kg": 10.500,
    "energy_j": 1.5e7,
    "speed_m_s": 1_700,
    "penetration_mm": {"100m": 600, "500m": 550},
    "lethal_armor_mm": 600,
    "notes": "Modern NATO MBT",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 120,
    "name": "120mm M829A2",
    "type": "APFSDS",
    "mass_kg": 10.400,
    "energy_j": 1.5e7,
    "speed_m_s": 1_700,
    "penetration_mm": {"100m": 650, "500m": 600},
    "lethal_armor_mm": 650,
    "notes": "US MBT round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 125,
    "name": "125mm 3BM44 APFSDS",
    "type": "APFSDS",
    "mass_kg": 8.500,
    "energy_j": 1.3e7,
    "speed_m_s": 1_700,
    "penetration_mm": {"100m": 550, "500m": 500},
    "lethal_armor_mm": 550,
    "notes": "Russian T-90 tank",
    "source": "BBTI"
  },
  {
    "caliber_mm": 125,
    "name": "125mm HEAT-FS",
    "type": "HEAT-FS",
    "mass_kg": 9.000,
    "energy_j": 1.1e7,
    "speed_m_s": 1_650,
    "penetration_mm": {"100m": 700, "500m": 650},
    "lethal_armor_mm": 700,
    "notes": "Russian T-80/T-90",
    "source": "BBTI"
  },
  {
    "caliber_mm": 140,
    "name": "140mm APFSDS",
    "type": "APFSDS",
    "mass_kg": 10.500,
    "energy_j": 2.0e7,
    "speed_m_s": 1_700,
    "penetration_mm": {"100m": 750, "500m": 700},
    "lethal_armor_mm": 750,
    "notes": "Experimental German MBT",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 155,
    "name": "155mm M829A1 HEAT",
    "type": "HEAT",
    "mass_kg": 43.000,
    "energy_j": 4.5e6,
    "speed_m_s": 800,
    "penetration_mm": {"100m": 500, "500m": 450},
    "lethal_armor_mm": 500,
    "notes": "US MBT HEAT",
    "source": "SteelBeasts"
  }
]
[
  {
    "vehicle_name": "T-72B3",
    "type": "Main Battle Tank",
    "armor_mm": 650,
    "weight_tons": 46,
    "max_speed_kph": 60,
    "engine_power_hp": 1130,
    "crew": 3,
    "armor_material": "Composite + ERA",
    "notes": "Modernized Russian MBT",
    "source": "BBTI"
  },
  {
    "vehicle_name": "Leclerc",
    "type": "Main Battle Tank",
    "armor_mm": 700,
    "weight_tons": 57,
    "max_speed_kph": 72,
    "engine_power_hp": 1500,
    "crew": 3,
    "armor_material": "Composite + ERA",
    "notes": "French MBT",
    "source": "BBTI"
  },
  {
    "vehicle_name": "Merkava Mk4",
    "type": "Main Battle Tank",
    "armor_mm": 800,
    "weight_tons": 65,
    "max_speed_kph": 60,
    "engine_power_hp": 1500,
    "crew": 4,
    "armor_material": "Composite + ERA",
    "notes": "Israeli MBT",
    "source": "BBTI"
  },
  {
    "vehicle_name": "ZTZ-99",
    "type": "Main Battle Tank",
    "armor_mm": 700,
    "weight_tons": 54,
    "max_speed_kph": 80,
    "engine_power_hp": 1200,
    "crew": 3,
    "armor_material": "Composite + ERA",
    "notes": "Chinese MBT",
    "source": "BBTI"
  },
  {
    "vehicle_name": "T-64B",
    "type": "Main Battle Tank",
    "armor_mm": 550,
    "weight_tons": 42,
    "max_speed_kph": 60,
    "engine_power_hp": 700,
    "crew": 3,
    "armor_material": "Composite",
    "notes": "Soviet MBT",
    "source": "BBTI"
  }
]
[
  {
    "caliber_mm": 203,
    "name": "203mm M107 HE",
    "type": "HE",
    "mass_kg": 90.000,
    "energy_j": 2.5e6,
    "speed_m_s": 570,
    "penetration_mm": {"100m": 50, "500m": 45},
    "lethal_armor_mm": 50,
    "notes": "US 8-inch artillery shell",
    "source": "BBTI"
  },
  {
    "caliber_mm": 210,
    "name": "210mm M-84 AP",
    "type": "AP",
    "mass_kg": 110.000,
    "energy_j": 3.0e6,
    "speed_m_s": 520,
    "penetration_mm": {"100m": 60, "500m": 55},
    "lethal_armor_mm": 60,
    "notes": "Soviet heavy artillery AP",
    "source": "BBTI"
  },
  {
    "caliber_mm": 240,
    "name": "240mm M1 AP",
    "type": "AP",
    "mass_kg": 140.000,
    "energy_j": 4.0e6,
    "speed_m_s": 510,
    "penetration_mm": {"100m": 80, "500m": 70},
    "lethal_armor_mm": 80,
    "notes": "US super-heavy artillery",
    "source": "BBTI"
  },
  {
    "caliber_mm": 280,
    "name": "280mm K5 AP",
    "type": "AP",
    "mass_kg": 220.000,
    "energy_j": 5.5e6,
    "speed_m_s": 400,
    "penetration_mm": {"100m": 100, "500m": 90},
    "lethal_armor_mm": 100,
    "notes": "WW2 German siege gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 305,
    "name": "305mm M1917 AP",
    "type": "AP",
    "mass_kg": 250.000,
    "energy_j": 6.0e6,
    "speed_m_s": 420,
    "penetration_mm": {"100m": 120, "500m": 110},
    "lethal_armor_mm": 120,
    "notes": "US coastal defense",
    "source": "BBTI"
  },
  {
    "caliber_mm": 381,
    "name": "381mm AP Mark 1",
    "type": "AP",
    "mass_kg": 880.000,
    "energy_j": 2.0e7,
    "speed_m_s": 700,
    "penetration_mm": {"100m": 350, "500m": 300},
    "lethal_armor_mm": 350,
    "notes": "WW2 battleship gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 406,
    "name": "406mm AP Mk8",
    "type": "AP",
    "mass_kg": 1_030.000,
    "energy_j": 2.5e7,
    "speed_m_s": 760,
    "penetration_mm": {"100m": 400, "500m": 350},
    "lethal_armor_mm": 400,
    "notes": "British battleship gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 420,
    "name": "420mm Gamma AP",
    "type": "AP",
    "mass_kg": 1_150.000,
    "energy_j": 3.0e7,
    "speed_m_s": 750,
    "penetration_mm": {"100m": 450, "500m": 400},
    "lethal_armor_mm": 450,
    "notes": "Experimental heavy artillery",
    "source": "BBTI"
  },
  {
    "caliber_mm": 450,
    "name": "450mm Super Heavy AP",
    "type": "AP",
    "mass_kg": 1_600.000,
    "energy_j": 4.0e7,
    "speed_m_s": 680,
    "penetration_mm": {"100m": 500, "500m": 450},
    "lethal_armor_mm": 500,
    "notes": "Experimental WW2 German gun",
    "source": "Panzerworld"
  },
  {
    "caliber_mm": 500,
    "name": "500mm Ultra Heavy Shell",
    "type": "AP",
    "mass_kg": 2_500.000,
    "energy_j": 6.0e7,
    "speed_m_s": 600,
    "penetration_mm": {"100m": 600, "500m": 550},
    "lethal_armor_mm": 600,
    "notes": "Super-heavy theoretical artillery",
    "source": "BBTI"
  }
]
[
  {
    "vehicle_name": "Panther II",
    "type": "Main Battle Tank",
    "armor_mm": 100,
    "weight_tons": 45,
    "max_speed_kph": 55,
    "engine_power_hp": 700,
    "crew": 5,
    "armor_material": "Homogeneous steel",
    "notes": "WW2 German experimental MBT",
    "source": "Panzerworld"
  },
  {
    "vehicle_name": "KV-3",
    "type": "Heavy Tank",
    "armor_mm": 130,
    "weight_tons": 55,
    "max_speed_kph": 35,
    "engine_power_hp": 700,
    "crew": 6,
    "armor_material": "Cast + welded steel",
    "notes": "Soviet heavy tank prototype",
    "source": "BBTI"
  },
  {
    "vehicle_name": "T28 Super Heavy",
    "type": "Super Heavy Tank",
    "armor_mm": 305,
    "weight_tons": 95,
    "max_speed_kph": 14,
    "engine_power_hp": 750,
    "crew": 6,
    "armor_material": "Steel",
    "notes": "US experimental heavy tank",
    "source": "BBTI"
  },
  {
    "vehicle_name": "Maus",
    "type": "Super Heavy Tank",
    "armor_mm": 240,
    "weight_tons": 188,
    "max_speed_kph": 20,
    "engine_power_hp": 1_200,
    "crew": 6,
    "armor_material": "Steel + composite",
    "notes": "WW2 German super-heavy tank",
    "source": "Panzerworld"
  },
  {
    "vehicle_name": "Object 279",
    "type": "Heavy Tank",
    "armor_mm": 220,
    "weight_tons": 60,
    "max_speed_kph": 55,
    "engine_power_hp": 1_000,
    "crew": 5,
    "armor_material": "Composite",
    "notes": "Soviet experimental MBT",
    "source": "BBTI"
  }
]
[
  {
    "caliber_mm": 120,
    "name": "120mm XM1111 APFSDS-T",
    "type": "APFSDS-T",
    "mass_kg": 10.700,
    "energy_j": 1.55e7,
    "speed_m_s": 1_750,
    "penetration_mm": {"100m": 670, "500m": 620},
    "lethal_armor_mm": 670,
    "notes": "US experimental MBT round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 125,
    "name": "125mm 3BM59 APFSDS",
    "type": "APFSDS",
    "mass_kg": 9.000,
    "energy_j": 1.4e7,
    "speed_m_s": 1_720,
    "penetration_mm": {"100m": 580, "500m": 540},
    "lethal_armor_mm": 580,
    "notes": "Russian T-90 modern round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 125,
    "name": "125mm 3BK21 HEAT",
    "type": "HEAT",
    "mass_kg": 9.500,
    "energy_j": 1.1e7,
    "speed_m_s": 1_600,
    "penetration_mm": {"100m": 750, "500m": 700},
    "lethal_armor_mm": 750,
    "notes": "Russian tandem HEAT for MBT",
    "source": "BBTI"
  },
  {
    "caliber_mm": 140,
    "name": "140mm Rheinmetall APFSDS",
    "type": "APFSDS",
    "mass_kg": 10.600,
    "energy_j": 2.05e7,
    "speed_m_s": 1_750,
    "penetration_mm": {"100m": 760, "500m": 720},
    "lethal_armor_mm": 760,
    "notes": "Experimental German MBT round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 152,
    "name": "152mm M830A1 HEAT",
    "type": "HEAT",
    "mass_kg": 43.000,
    "energy_j": 5.0e6,
    "speed_m_s": 900,
    "penetration_mm": {"100m": 650, "500m": 600},
    "lethal_armor_mm": 650,
    "notes": "US MBT HEAT round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 105,
    "name": "105mm XM900 MPAT",
    "type": "MPAT",
    "mass_kg": 12.200,
    "energy_j": 7.0e6,
    "speed_m_s": 1_500,
    "penetration_mm": {"100m": 470, "500m": 430},
    "lethal_armor_mm": 470,
    "notes": "US experimental guided MBT round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 120,
    "name": "120mm DM63 APFSDS",
    "type": "APFSDS",
    "mass_kg": 10.500,
    "energy_j": 1.5e7,
    "speed_m_s": 1_680,
    "penetration_mm": {"100m": 630, "500m": 590},
    "lethal_armor_mm": 630,
    "notes": "German Leopard 2 modern round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 120,
    "name": "120mm DM11 HE-MP",
    "type": "HE-MP",
    "mass_kg": 12.300,
    "energy_j": 6.0e6,
    "speed_m_s": 1_050,
    "penetration_mm": {"100m": 80, "500m": 60},
    "lethal_armor_mm": 80,
    "notes": "High explosive multi-purpose modern MBT round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 152,
    "name": "152mm XM1113 APFSDS",
    "type": "APFSDS",
    "mass_kg": 42.000,
    "energy_j": 1.8e7,
    "speed_m_s": 1_600,
    "penetration_mm": {"100m": 750, "500m": 700},
    "lethal_armor_mm": 750,
    "notes": "Experimental US MBT round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 155,
    "name": "155mm M795 HE",
    "type": "HE",
    "mass_kg": 43.000,
    "energy_j": 5.0e6,
    "speed_m_s": 850,
    "penetration_mm": {"100m": 50, "500m": 45},
    "lethal_armor_mm": 50,
    "notes": "US modern artillery shell",
    "source": "SteelBeasts"
  }
]
[
  {
    "vehicle_name": "Leopard 3 Concept",
    "type": "Main Battle Tank",
    "armor_mm": 850,
    "weight_tons": 70,
    "max_speed_kph": 75,
    "engine_power_hp": 1_800,
    "crew": 3,
    "armor_material": "Next-gen composite + ERA",
    "notes": "Fictional/Experimental future MBT",
    "source": "SteelBeasts"
  },
  {
    "vehicle_name": "T-14 Armata",
    "type": "Main Battle Tank",
    "armor_mm": 900,
    "weight_tons": 55,
    "max_speed_kph": 80,
    "engine_power_hp": 1_500,
    "crew": 3,
    "armor_material": "Composite + ERA",
    "notes": "Modern Russian MBT",
    "source": "BBTI"
  },
  {
    "vehicle_name": "M1A3 Abrams Concept",
    "type": "Main Battle Tank",
    "armor_mm": 950,
    "weight_tons": 63,
    "max_speed_kph": 72,
    "engine_power_hp": 1_800,
    "crew": 4,
    "armor_material": "Composite + advanced ERA",
    "notes": "US next-gen MBT concept",
    "source": "SteelBeasts"
  },
  {
    "vehicle_name": "K2 Black Panther",
    "type": "Main Battle Tank",
    "armor_mm": 850,
    "weight_tons": 55,
    "max_speed_kph": 70,
    "engine_power_hp": 1_500,
    "crew": 3,
    "armor_material": "Composite + ERA",
    "notes": "South Korean MBT",
    "source": "BBTI"
  },
  {
    "vehicle_name": "Type 99A",
    "type": "Main Battle Tank",
    "armor_mm": 900,
    "weight_tons": 54,
    "max_speed_kph": 80,
    "engine_power_hp": 1_500,
    "crew": 3,
    "armor_material": "Composite + ERA",
    "notes": "Modern Chinese MBT",
    "source": "BBTI"
  }
]
[
  {
    "caliber_mm": 20,
    "name": "M61 Vulcan AP-T",
    "type": "AP-T",
    "mass_kg": 0.101,
    "energy_j": 1.5e4,
    "speed_m_s": 1_050,
    "penetration_mm": {"10m": 5},
    "lethal_armor_mm": 5,
    "notes": "US 20mm aircraft cannon round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 30,
    "name": "ADEN 30mm HE",
    "type": "HE",
    "mass_kg": 0.275,
    "energy_j": 3.2e4,
    "speed_m_s": 790,
    "penetration_mm": {"10m": 8},
    "lethal_armor_mm": 8,
    "notes": "British aircraft cannon high-explosive round",
    "source": "BBTI"
  },
  {
    "caliber_mm": 30,
    "name": "ADEN 30mm AP",
    "type": "AP",
    "mass_kg": 0.285,
    "energy_j": 3.4e4,
    "speed_m_s": 790,
    "penetration_mm": {"10m": 15},
    "lethal_armor_mm": 15,
    "notes": "British aircraft cannon armor-piercing",
    "source": "BBTI"
  },
  {
    "caliber_mm": 25,
    "name": "M242 Bushmaster APDS-T",
    "type": "APDS-T",
    "mass_kg": 0.185,
    "energy_j": 2.8e4,
    "speed_m_s": 1_080,
    "penetration_mm": {"10m": 12},
    "lethal_armor_mm": 12,
    "notes": "US 25mm autocannon aircraft & vehicle round",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 30,
    "name": "GAU-8 Avenger AP",
    "type": "AP",
    "mass_kg": 0.39,
    "energy_j": 4.5e4,
    "speed_m_s": 1_010,
    "penetration_mm": {"10m": 20},
    "lethal_armor_mm": 20,
    "notes": "A-10 Warthog cannon",
    "source": "BBTI"
  }
]
[
  {
    "caliber_mm": 127,
    "name": "5-inch/54 Mk 45 HE",
    "type": "HE",
    "mass_kg": 32.0,
    "energy_j": 5.0e5,
    "speed_m_s": 790,
    "penetration_mm": {"100m": 25},
    "lethal_armor_mm": 25,
    "notes": "US modern destroyer gun shell",
    "source": "BBTI"
  },
  {
    "caliber_mm": 127,
    "name": "5-inch/54 Mk 45 AP",
    "type": "AP",
    "mass_kg": 32.5,
    "energy_j": 5.2e5,
    "speed_m_s": 790,
    "penetration_mm": {"100m": 50},
    "lethal_armor_mm": 50,
    "notes": "US modern destroyer armor-piercing shell",
    "source": "BBTI"
  },
  {
    "caliber_mm": 152,
    "name": "152mm MLRS HE",
    "type": "HE",
    "mass_kg": 90.0,
    "energy_j": 1.2e6,
    "speed_m_s": 850,
    "penetration_mm": {"100m": 30},
    "lethal_armor_mm": 30,
    "notes": "Soviet MLRS artillery rocket",
    "source": "BBTI"
  },
  {
    "caliber_mm": 227,
    "name": "227mm M270 MLRS HE",
    "type": "HE",
    "mass_kg": 170.0,
    "energy_j": 2.5e6,
    "speed_m_s": 1_000,
    "penetration_mm": {"100m": 35},
    "lethal_armor_mm": 35,
    "notes": "US MLRS artillery rocket",
    "source": "SteelBeasts"
  },
  {
    "caliber_mm": 240,
    "name": "240mm M-240 Rocket HE",
    "type": "HE",
    "mass_kg": 200.0,
    "energy_j": 2.7e6,
    "speed_m_s": 950,
    "penetration_mm": {"100m": 40},
    "lethal_armor_mm": 40,
    "notes": "Soviet/Russian MLRS rocket",
    "source": "BBTI"
  }
]
